package net.chriskatze.katzencraft.entity.client.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class BulbasaurAnimations {
    public static final Animation BULBASAUR_GROUND_IDLE = Animation.Builder.create(0.9999999999999996f).looping()
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bulb",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-0.5f, 0f, 1.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0.5f, 0f, -1.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation BULBASAUR_GROUND_WALK = Animation.Builder.create(0.7407407407407408f).looping()
            .addBoneAnimation("bulbasaur",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3703703703703704f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1234567901234568f, AnimationHelper.createTranslationalVector(0f, 1f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2160493827160494f, AnimationHelper.createTranslationalVector(0f, 1.7f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.308641975308642f, AnimationHelper.createTranslationalVector(0f, 2.2f, -0.83f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4320987654320988f, AnimationHelper.createTranslationalVector(0f, 1.4f, -0.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5864197530864198f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1234567901234568f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2160493827160494f, AnimationHelper.createRotationalVector(-13.25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4320987654320988f, AnimationHelper.createRotationalVector(4.17f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5864197530864198f, AnimationHelper.createRotationalVector(16.62f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6790123456790124f, AnimationHelper.createRotationalVector(12.09f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bulb",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3703703703703704f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bulb",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.308641975308642f, AnimationHelper.createRotationalVector(-11.67f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3703703703703704f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.617283950617284f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_front_right",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createTranslationalVector(0f, 0.8f, -0.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2469135802469136f, AnimationHelper.createTranslationalVector(0f, 1.6f, -0.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_front_right",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1234567901234568f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4012345679012346f, AnimationHelper.createRotationalVector(-49.03f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6481481481481481f, AnimationHelper.createRotationalVector(-14.17f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_front_left",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createTranslationalVector(0f, 0.8f, -0.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2469135802469136f, AnimationHelper.createTranslationalVector(0f, 1.6f, -0.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_front_left",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1234567901234568f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4012345679012346f, AnimationHelper.createRotationalVector(-49.03f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6481481481481481f, AnimationHelper.createRotationalVector(-14.17f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_back_right",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2469135802469136f, AnimationHelper.createTranslationalVector(0f, 1.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3703703703703704f, AnimationHelper.createTranslationalVector(0f, 1.13f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5864197530864198f, AnimationHelper.createTranslationalVector(0f, 1.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_back_right",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.46296296296296297f, AnimationHelper.createRotationalVector(-16.25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5864197530864198f, AnimationHelper.createRotationalVector(-24.77f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6790123456790124f, AnimationHelper.createRotationalVector(-14.03f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_back_left",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2469135802469136f, AnimationHelper.createTranslationalVector(0f, 1.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3703703703703704f, AnimationHelper.createTranslationalVector(0f, 1.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5864197530864198f, AnimationHelper.createTranslationalVector(0f, 1.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg_back_left",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1851851851851852f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.46296296296296297f, AnimationHelper.createRotationalVector(-16.25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5864197530864198f, AnimationHelper.createRotationalVector(-24.77f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6790123456790124f, AnimationHelper.createRotationalVector(-14.03f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7407407407407408f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
}